### ISSUE TITLE
Image link broken

### ISSUE THREAD

**Issue by Aatmaj-Zephyr** [R-Lovelett/dog-ownership-website#1]
![Capture](https://user-images.githubusercontent.com/83284294/194535744-8013bed6-3842-47e9-a29c-8d3a24f0ce54.PNG)

**Comment by R-Lovelett** [comment]
Thank you for bringing this to my attention. Updated code with fixed images should be live soon.

**Comment by R-Lovelett** [comment]
![image](https://user-images.githubusercontent.com/83929892/194590566-7bbe882b-0e97-419c-9eeb-e212232891f2.png)
New image located, and other links were fixed so hopefully this won't happen again. Thank you for letting me know. 😊
